import os
from dotenv import load_dotenv

load_dotenv()

GET_IP_URL=os.getenv("GET_IP_URL")
BASE_API_URL=os.getenv("BASE_API_URL")
API_TOKEN_KENTOES_DOT_COM=os.getenv("API_TOKEN_KENTOES_DOT_COM")
ZONE_ID_KENTOES_DOT_COM=os.getenv("ZONE_ID_KENTOES_DOT_COM")
RECORD_ID_KENTOES_DOT_COM=os.getenv("RECORD_ID_KENTOES_DOT_COM")
DOMAIN_KENTOES_DOT_COM=os.getenv("DOMAIN_KENTOES_DOT_COM")
EMAIL_KENTOES_DOT_COM=os.getenv("EMAIL_KENTOES_DOT_COM")